Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,3 +4,60 @@ on:
   push:
     branches:
       - master
+
+jobs:
+  build-and-push-docker-image:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Checkout Code
+      uses: actions/checkout@v3
+
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v2
+
+    - name: Log in to Docker Hub
+      uses: docker/login-action@v2
+      with:
+        username: ${{ secrets.DOCKER_USERNAME }}
+        password: ${{ secrets.DOCKER_PASSWORD }}
+
+    - name: Build and Push Docker Image
+      uses: docker/build-push-action@v5
+      with:
+        push: true
+        tags: |
+          ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest
+          ${{ secrets.DOCKER_USERNAME }}/nodejs-app:${{ github.sha }}
+
+  deploy:
+   runs-on: ubuntu-latest
+   needs: build-and-push-docker-image
+
+   steps:
+    - name: Add SSH Private Key
+      uses: webfactory/ssh-agent@v0.7.0
+      with:
+        ssh-private-key: ${{ secrets.SSH_KEY }}
+
+    - name: Deploy to Server
+      run: |
+        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
+        echo "Connected to EC2 instance!"
+        sudo docker stop angular-app || true
+        sudo docker rm angular-app || true
+        sudo docker container prune -f
+        sudo docker images prune -f
+        
+        sudo docker pull ${{ secrets.DOCKER_USERNAME }}/angular-app:latest
+        sudo docker run -d --name angular-app -p 80:80 --restart always ${{ secrets.DOCKER_USERNAME }}/angular-app:latest
+
+    - name: Notify on Success
+      if: success()
+      run: |
+        echo "Deployment Successful!"
+
+    - name: Notify on Failure
+      if: failure()
+      run: |
+        echo "Deployment Failed!"
